"""Build resource-level migration reports and an offline analyst review.

The batch manifest is the source of truth.  This module only projects its
review metadata for the JSON/Markdown reports: it never loads or prints
SQL/notebook bodies, query results, tokens, credential-like values, or local
machine paths there.
The optional HTML report intentionally embeds changed code hunks so an analyst
can review every resource in one offline file.
"""

from __future__ import annotations

import copy
import difflib
import hashlib
import html
import json
import re
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable, Mapping

from .migration_batch import BATCH_SCHEMA_VERSION, BatchError, build_batch_digest, validate_batch_manifest
from .notebooks import NotebookError
from .review import build_review_model
from .task import TaskError, baseline_file, preview_notebook_task
from .workspace import WorkspaceError, read_manifest


REPORT_SCHEMA_VERSION = 1
DIFF_PAYLOAD_SCHEMA_VERSION = 1
_LOT_RE = re.compile(r"r\d{2}")


def _as_int(value: Any, default: int = 0) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


def _safe_warning(value: Mapping[str, Any]) -> dict[str, Any]:
    """Keep only content-free incident coordinates and classification fields."""
    keys = ("kind", "route", "path", "cell", "line", "statement_class", "rule", "start", "end")
    return {key: value[key] for key in keys if key in value and value[key] is not None}


def _safe_blocker(value: Mapping[str, Any]) -> dict[str, Any]:
    keys = ("kind", "path", "cell", "line", "rule")
    return {key: value[key] for key in keys if key in value and value[key] is not None}


def _route_rows(rewrite: Mapping[str, Any]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for item in rewrite.get("applied_routes") or []:
        if not isinstance(item, Mapping):
            continue
        rows.append(
            {
                "mapping_id": str(item.get("mapping_id") or ""),
                "old": str(item.get("old") or ""),
                "new": str(item.get("new") or ""),
                "occurrences": _as_int(item.get("occurrences")),
            }
        )
    return rows


def _unmatched_rows(record: Mapping[str, Any]) -> list[dict[str, Any]]:
    rewrite = record.get("rewrite") or {}
    incidents = [item for item in rewrite.get("incidents") or [] if isinstance(item, Mapping)]
    incidents = [item for item in incidents if str(item.get("kind") or "") == "unknown_route"]
    # Manifests generated by older QueryFlow versions may only have the
    # flattened warning list.  Use it as a compatibility fallback, but never
    # duplicate incidents that are already present in ``rewrite``.
    if not incidents:
        incidents = [item for item in record.get("warnings") or [] if isinstance(item, Mapping)]
        incidents = [item for item in incidents if str(item.get("kind") or "") == "unknown_route"]
    return [_safe_warning(item) for item in incidents]


def _review_link(lot: str, record: Mapping[str, Any]) -> str:
    relative = str(record.get("review_relative") or "").strip()
    return f"{lot}/{relative}" if relative else ""


def _resource_detail(lot: str, manifest_path: Path, record: Mapping[str, Any]) -> dict[str, Any]:
    resource = record.get("resource") or {}
    source = record.get("source") or {}
    destination = record.get("destination") or {}
    rewrite = record.get("rewrite") or {}
    classification = record.get("classification") or {}
    review = record.get("review") or {}
    published = record.get("published") or {}
    receipt = record.get("receipt") or {}
    audit = receipt.get("audit") or {}
    route_replacements = _route_rows(rewrite)
    unmatched_routes = _unmatched_rows(record)
    warnings = [
        _safe_warning(item)
        for item in (record.get("warnings") or [])
        if isinstance(item, Mapping)
    ]
    blockers = [
        _safe_blocker(item)
        for item in (record.get("blockers") or [])
        if isinstance(item, Mapping)
    ]
    resource_name = str(resource.get("name") or "")
    return {
        "lot": lot,
        "manifest": str(manifest_path),
        "ordinal": _as_int(record.get("ordinal")),
        "kind": str(resource.get("kind") or ""),
        "display_name": str(resource.get("display_name") or ""),
        "source_name": resource_name,
        "source_project": str(resource.get("project") or ""),
        "source_location": str(resource.get("location") or ""),
        "source_filename": str(source.get("filename") or ""),
        "source_head_commit": str(source.get("head_commit") or ""),
        "source_content_sha256": str(source.get("content_sha256") or ""),
        "destination_project": str(destination.get("project") or ""),
        "destination_location": str(destination.get("location") or ""),
        "destination_repository_id": str(destination.get("repository_id") or ""),
        "destination_display_name": str(destination.get("display_name") or ""),
        "destination_repository": str(published.get("repository") or destination.get("repository") or ""),
        "destination_collision": bool(destination.get("collision")),
        "status": str(record.get("status") or ""),
        "sealed_copy": bool(record.get("sealed_copy")),
        "redacted_review": bool(record.get("redacted_review")),
        "security": {
            "sealed": bool((record.get("security") or {}).get("sealed")),
            "secret_handling": str((record.get("security") or {}).get("secret_handling") or ""),
            "finding_count": _as_int((record.get("security") or {}).get("finding_count")),
        },
        "migration_eligible": bool(record.get("migration_eligible")),
        "execution_eligible": bool(record.get("execution_eligible")),
        "classification": {
            "statement_class": str(classification.get("statement_class") or ""),
            "read_only": bool(classification.get("read_only")),
            "references": [str(item) for item in (classification.get("references") or [])],
            "errors": [str(item) for item in (classification.get("errors") or [])],
            "warnings": [str(item) for item in (classification.get("warnings") or [])],
            "dynamic_cells": [_as_int(item) for item in (classification.get("dynamic_cells") or [])],
        },
        "review": {
            "required": bool(review.get("required")),
            "reasons": [str(item) for item in (review.get("reasons") or [])],
            "policy": str(review.get("policy") or ""),
        },
        "changed_files": [str(item) for item in (rewrite.get("changed_files") or record.get("changed_files") or [])],
        "route_replacements": route_replacements,
        "route_replacement_group_count": len(route_replacements),
        "route_replacement_occurrence_count": sum(item["occurrences"] for item in route_replacements),
        "unmatched_routes": unmatched_routes,
        "unmatched_route_count": len(unmatched_routes),
        "dynamic_cells": [_as_int(item) for item in (rewrite.get("dynamic_cells") or [])],
        "warnings": warnings,
        "blockers": blockers,
        "runtime_error": str(record.get("error") or ""),
        "before_sha256": str(rewrite.get("before_sha256") or ""),
        "proposed_sha256": str(rewrite.get("proposed_sha256") or record.get("proposed_sha256") or ""),
        "sql_executed": bool(rewrite.get("sql_executed") or (receipt.get("sql_executed") is True)),
        "published_commit_sha": str(published.get("commit_sha") or ""),
        "published_filename": str(published.get("filename") or source.get("filename") or ""),
        "audit": {
            "task_id": str(audit.get("task_id") or ""),
            "archived_at": str(audit.get("archived_at") or ""),
            "manifest_sha256": str(audit.get("manifest_sha256") or ""),
            "files": [str(item) for item in (audit.get("files") or [])],
        },
        "task": str(record.get("task") or ""),
        "review_file": str(record.get("review_file") or ""),
        "review_relative": _review_link(lot, record),
    }


def _campaign_base_id(campaign_id: Any) -> str:
    """Normalize the per-lot suffix used by batch campaign IDs."""
    value = str(campaign_id or "").strip()
    return re.sub(r"-r\d{2}$", "", value)


def _load_campaign_manifests(campaign_root: Path) -> list[tuple[str, Path, dict[str, Any]]]:
    paths = sorted(
        (
            path
            for path in campaign_root.glob("*/manifest.json")
            if path.parent != campaign_root and path.parent.is_dir()
        ),
        key=lambda path: path.parent.name,
    )
    if not paths:
        raise BatchError(f"No hay manifests de lote en {campaign_root}")
    loaded: list[tuple[str, Path, dict[str, Any]]] = []
    for path in paths:
        try:
            value = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as error:
            raise BatchError(f"No se pudo leer el manifest {path}: {error}") from error
        if not isinstance(value, dict):
            raise BatchError(f"El manifest {path} no es un objeto JSON")
        validate_batch_manifest(
            value,
            allow_blocked=True,
        )
        if str(value.get("publication_digest") or "") != build_batch_digest(value):
            raise BatchError(f"Digest inconsistente: {path}")
        loaded.append((path.parent.name, path, value))
    return loaded


def build_detailed_report(
    campaign_root: Path,
    *,
    expected_count: int | None = None,
    campaign_prefix: str | None = None,
) -> dict[str, Any]:
    """Project every resource and every route finding from all campaign lots."""
    campaign_root = Path(campaign_root).expanduser().resolve()
    manifests = _load_campaign_manifests(campaign_root)
    first_manifest = manifests[0][2]
    expected_campaign = _campaign_base_id(first_manifest.get("campaign_id"))
    expected_prefix = str(campaign_prefix or "").strip().rstrip("-")
    # Location is a lot-level property for multiregion campaigns.  Projects,
    # dictionary and operation must remain stable across every lot.
    scoped_fields = ("source_project", "destination_project", "dictionary_sha256")
    expected_scope = {
        field: str(first_manifest.get(field) or "")
        for field in scoped_fields
    }
    expected_operation = str(
        first_manifest.get("operation")
        or (first_manifest.get("selection") or {}).get("operation")
        or "copy"
    ).strip().casefold()
    locations: set[str] = set()
    for lot, manifest_path, manifest in manifests:
        actual_campaign = _campaign_base_id(manifest.get("campaign_id"))
        campaign_matches = (
            actual_campaign == expected_campaign
            if not expected_prefix
            else str(manifest.get("campaign_id") or "").startswith(expected_prefix + "-")
        )
        if not campaign_matches:
            raise BatchError(
                f"Los lotes pertenecen a campañas diferentes: {manifest_path} "
                f"({manifest.get('campaign_id')}) no coincide con {expected_campaign}"
            )
        mismatches = [
            field
            for field in scoped_fields
            if str(manifest.get(field) or "") != expected_scope[field]
        ]
        if mismatches:
            raise BatchError(
                f"El lote {lot} no comparte el alcance de la campaña con los demás "
                f"lotes ({', '.join(mismatches)}): {manifest_path}"
            )
        actual_operation = str(
            manifest.get("operation")
            or (manifest.get("selection") or {}).get("operation")
            or "copy"
        ).strip().casefold()
        if actual_operation != expected_operation:
            raise BatchError(
                f"El lote {lot} no comparte la operación de la campaña "
                f"({actual_operation} != {expected_operation}): {manifest_path}"
            )
        lot_location = str(
            manifest.get("destination_location") or manifest.get("location") or ""
        ).strip()
        if lot_location:
            locations.add(lot_location)
    resources: list[dict[str, Any]] = []
    lots: list[dict[str, Any]] = []
    campaign_ids: list[str] = []
    for lot, manifest_path, manifest in manifests:
        campaign_id = str(manifest.get("campaign_id") or "")
        campaign_ids.append(campaign_id)
        details = [
            _resource_detail(lot, manifest_path, item)
            for item in (manifest.get("resources") or [])
            if isinstance(item, Mapping)
        ]
        resources.extend(details)
        lots.append(
            {
                "lot": lot,
                "campaign_id": campaign_id,
                "operation": str(
                    manifest.get("operation")
                    or (manifest.get("selection") or {}).get("operation")
                    or "copy"
                ),
                "location": str(
                    manifest.get("destination_location") or manifest.get("location") or ""
                ),
                "manifest": str(manifest_path),
                "report_markdown": str(manifest_path.with_name("migration-report.md")),
                "review": str(manifest_path.with_name("review.html")),
                "status": str(manifest.get("status") or ""),
                "resource_count": len(details),
                "published_count": sum(item["status"] == "published" for item in details),
                "completed_count": sum(
                    item["status"] in {"published", "published_verified", "already_present_identical", "already_compliant"}
                    for item in details
                ),
                "pending_count": sum(
                    item["status"] in {
                        "pending", "prepared", "ready_to_update", "security_pending",
                        "blocked", "destination_conflict", "failed",
                    }
                    for item in details
                ),
                "warning_count": len(manifest.get("warnings") or []),
                "publication_digest": str(manifest.get("publication_digest") or ""),
            }
        )
    if expected_count is not None and len(resources) != int(expected_count):
        raise BatchError(f"Se esperaban {expected_count} recursos; se encontraron {len(resources)}")
    keys = [(item["kind"], item["source_name"]) for item in resources]
    if len(keys) != len(set(keys)):
        raise BatchError("La campaña contiene recursos duplicados")

    route_groups: dict[tuple[str, str, str], dict[str, Any]] = {}
    unmatched: list[dict[str, Any]] = []
    for item in resources:
        resource_key = f"{item['lot']}/{item['ordinal']:02d} {item['display_name']}"
        for route in item["route_replacements"]:
            key = (route["mapping_id"], route["old"], route["new"])
            aggregate = route_groups.setdefault(
                key,
                {
                    "mapping_id": route["mapping_id"],
                    "old": route["old"],
                    "new": route["new"],
                    "occurrences": 0,
                    "resources": [],
                },
            )
            aggregate["occurrences"] += route["occurrences"]
            if resource_key not in aggregate["resources"]:
                aggregate["resources"].append(resource_key)
        for route in item["unmatched_routes"]:
            unmatched.append(
                {
                    "lot": item["lot"],
                    "ordinal": item["ordinal"],
                    "resource": item["display_name"],
                    **route,
                }
            )

    status_counts = Counter(item["status"] or "unknown" for item in resources)
    kind_counts = Counter(item["kind"] or "unknown" for item in resources)
    class_counts = Counter(item["classification"]["statement_class"] or "not_evaluated" for item in resources)
    warning_counts = Counter(
        str(warning.get("kind") or "unknown")
        for item in resources
        for warning in item["warnings"]
    )
    review_reason_counts = Counter(
        reason
        for item in resources
        for reason in item["review"]["reasons"]
    )
    first = campaign_ids[0] if campaign_ids else campaign_root.name
    campaign_id = expected_prefix or _campaign_base_id(first) or campaign_root.name
    return {
        "schema_version": REPORT_SCHEMA_VERSION,
        "source_schema_version": BATCH_SCHEMA_VERSION,
        "campaign_id": campaign_id,
        "campaign_root": str(campaign_root),
        "generated_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "source_project": str(manifests[0][2].get("source_project") or ""),
        "destination_project": str(manifests[0][2].get("destination_project") or ""),
        "operation": expected_operation,
        "location": next(iter(locations)) if len(locations) == 1 else "varias",
        "locations": sorted(locations),
        "resource_count": len(resources),
        "published_count": status_counts.get("published", 0),
        "completed_count": sum(
            status_counts.get(status, 0)
            for status in ("published", "published_verified", "already_present_identical", "already_compliant")
        ),
        "pending_count": sum(
            status_counts.get(status, 0)
            for status in (
                "pending", "prepared", "ready_to_update", "security_pending",
                "blocked", "destination_conflict", "failed",
            )
        ),
        "status_counts": dict(sorted(status_counts.items())),
        "kind_counts": dict(sorted(kind_counts.items())),
        "classification_counts": dict(sorted(class_counts.items())),
        "warning_counts": dict(sorted(warning_counts.items())),
        "review_reason_counts": dict(sorted(review_reason_counts.items())),
        "review_required_count": sum(item["review"]["required"] for item in resources),
        "execution_eligible_count": sum(item["execution_eligible"] for item in resources),
        "sql_executed": any(item["sql_executed"] for item in resources),
        "changed_file_count": sum(len(item["changed_files"]) for item in resources),
        "route_replacement_group_count": sum(item["route_replacement_group_count"] for item in resources),
        "route_replacement_occurrence_count": sum(item["route_replacement_occurrence_count"] for item in resources),
        "unique_route_replacement_group_count": len(route_groups),
        "unmatched_route_count": len(unmatched),
        "unique_unmatched_route_count": len({str(item.get("route") or "") for item in unmatched}),
        "route_replacement_group_count_definition": "Una aplicación de una regla del diccionario por recurso o celda; no es una regla única.",
        "unmatched_route_count_definition": "Incidentes únicos por recurso y cadena de ruta; la misma cadena repetida dentro de un recurso se deduplica.",
        "pending_resources": [
            item["display_name"]
            for item in resources
            if item["status"]
            in {
                "pending", "prepared", "ready_to_update", "security_pending",
                "blocked", "destination_conflict", "failed",
            }
        ],
        "lots": lots,
        "route_replacements": sorted(
            route_groups.values(),
            key=lambda item: (item["mapping_id"], item["old"], item["new"]),
        ),
        "unmatched_routes": unmatched,
        "resources": resources,
    }


def _md(value: Any) -> str:
    text = str(value if value is not None else "")
    return text.replace("|", "\\|").replace("\n", " ").replace("`", "' ")


def _portable_path(value: Any) -> str:
    """Keep a useful relative filename while never exporting local roots."""
    text = str(value or "").strip()
    if not text:
        return ""
    path = Path(text)
    return path.name if path.is_absolute() else text


def _portable_review_reference(lot: str, value: Any) -> str:
    text = _portable_path(value)
    if not text:
        return ""
    prefix = f"{lot}/" if lot else ""
    return text if not prefix or text.startswith(prefix) else f"{prefix}{text}"


def _portable_report(report: Mapping[str, Any]) -> dict[str, Any]:
    """Project report metadata without machine-local paths.

    The in-memory report remains rich enough for the diff builder.  JSON and
    Markdown are portable analyst hand-offs, so they expose only relative
    references (for example ``r01/manifest.json``) and omit local roots.
    """
    portable = copy.deepcopy(dict(report))
    portable.pop("campaign_root", None)
    portable["path_policy"] = "Se omitieron rutas locales; se conservan referencias relativas por lote."

    portable_lots: list[dict[str, Any]] = []
    for raw_lot in portable.get("lots") or []:
        if not isinstance(raw_lot, Mapping):
            continue
        lot = dict(raw_lot)
        lot_name = str(lot.get("lot") or "")
        lot.pop("manifest", None)
        lot.pop("report_markdown", None)
        lot.pop("review", None)
        if lot_name:
            lot["manifest_relative"] = f"{lot_name}/manifest.json"
            lot["report_markdown_relative"] = f"{lot_name}/migration-report.md"
            lot["review_relative"] = f"{lot_name}/review.html"
        portable_lots.append(lot)
    portable["lots"] = portable_lots

    portable_resources: list[dict[str, Any]] = []
    for raw_item in portable.get("resources") or []:
        if not isinstance(raw_item, Mapping):
            continue
        item = dict(raw_item)
        lot_name = str(item.get("lot") or "")
        audit = item.get("audit")
        audit_copy = dict(audit) if isinstance(audit, Mapping) else {}
        task_id = str(audit_copy.get("task_id") or "").strip()
        if not task_id:
            task_id = Path(str(item.get("task") or "")).name
        item.pop("manifest", None)
        item.pop("task", None)
        item.pop("review_file", None)
        item["source_filename"] = _portable_path(item.get("source_filename"))
        item["published_filename"] = _portable_path(item.get("published_filename"))
        item["changed_files"] = [
            _portable_path(value) for value in (item.get("changed_files") or [])
        ]
        for field in ("unmatched_routes", "warnings", "blockers"):
            entries = item.get(field)
            if not isinstance(entries, list):
                continue
            safe_entries: list[Any] = []
            for entry in entries:
                if not isinstance(entry, Mapping):
                    safe_entries.append(entry)
                    continue
                entry_copy = dict(entry)
                if "path" in entry_copy:
                    entry_copy["path"] = _portable_path(entry_copy.get("path"))
                safe_entries.append(entry_copy)
            item[field] = safe_entries
        if isinstance(audit, Mapping):
            audit_copy["files"] = [
                Path(str(value)).name for value in (audit.get("files") or [])
            ]
            item["audit"] = audit_copy
        if lot_name:
            item["manifest_relative"] = f"{lot_name}/manifest.json"
            item["task_relative"] = f"{lot_name}/{Path(task_id).name}" if task_id else ""
        item["review_relative"] = _portable_review_reference(
            lot_name, item.get("review_relative")
        )
        portable_resources.append(item)
    portable["resources"] = portable_resources
    return portable


def _list_or_none(values: Iterable[Any], empty: str) -> list[str]:
    result = [str(value) for value in values if str(value)]
    return result or [empty]


def _render_route_table(routes: list[Mapping[str, Any]], *, unmatched: bool = False) -> list[str]:
    if unmatched:
        if not routes:
            return ["No se encontraron rutas fuera del diccionario en este recurso.", ""]
        lines = [
            "| Ruta no encontrada | Archivo/celda | Línea | Posición |",
            "|---|---|---:|---:|",
        ]
        for item in routes:
            path = str(item.get("path") or "-")
            if item.get("cell") is not None:
                path += f" · celda {item['cell']}"
            position = "-"
            if item.get("start") is not None or item.get("end") is not None:
                position = f"{item.get('start', '-')}–{item.get('end', '-')}"
            lines.append(
                f"| `{_md(item.get('route') or '-')}` | `{_md(path)}` | {_md(item.get('line') or '-')} | {_md(position)} |"
            )
        return lines + [""]
    if not routes:
        return ["Ninguna ruta del diccionario coincidió en este recurso.", ""]
    lines = [
        "| ID | Ruta original | Ruta nueva | Ocurrencias |",
        "|---|---|---|---:|",
    ]
    for item in routes:
        lines.append(
            f"| `{_md(item.get('mapping_id') or '-')}` | `{_md(item.get('old') or '-')}` | `{_md(item.get('new') or '-')}` | {_md(item.get('occurrences', 0))} |"
        )
    return lines + [""]


def render_detailed_markdown(report: Mapping[str, Any]) -> str:
    """Render a complete analyst-facing report without embedding code bodies."""
    report = _portable_report(report)
    resources = list(report.get("resources") or [])
    lines = [
        f"# Reporte detallado de migración: `{_md(report.get('campaign_id') or '')}`",
        "",
        f"Este reporte consolida {len(report.get('lots') or [])} lotes a nivel de recurso. Contiene rutas aplicadas, rutas no encontradas, coordenadas de revisión, hashes y auditoría; no contiene SQL completo, filas, tokens ni credenciales.",
        "",
        f"- Operación: **{_md(report.get('operation') or 'copy')}** · origen: `{_md(report.get('source_project'))}` · destino: `{_md(report.get('destination_project'))}` · regiones: `{_md(', '.join(report.get('locations') or [report.get('location') or '']))}`",
        f"- Recursos: **{report.get('resource_count', 0)}** · completados/verificados: **{report.get('completed_count', report.get('published_count', 0))}** · pendientes/revisión: **{report.get('pending_count', 0)}**",
        f"- Aplicaciones de reglas: **{report.get('route_replacement_group_count', 0)}** grupos ({report.get('unique_route_replacement_group_count', 0)} combinaciones únicas) · **{report.get('route_replacement_occurrence_count', 0)}** reemplazos textuales",
        f"- Incidentes de ruta no encontrada: **{report.get('unmatched_route_count', 0)}** (rutas únicas: **{report.get('unique_unmatched_route_count', 0)}**)",
        f"- Archivos/celdas modificados: **{report.get('changed_file_count', 0)}** · SQL ejecutado: **no**",
        f"- Revisión humana requerida: **{report.get('review_required_count', 0)}**",
        "",
        "## Cómo usarlo",
        "",
        "1. Busca el recurso en el índice o usa la búsqueda del editor sobre este archivo.",
        "2. Dentro de su sección revisa las tablas **Rutas reemplazadas** e **Incidentes de ruta no encontrada**.",
        "3. Abre el enlace **Diff** para ver las líneas/celdas en rojo y verde.",
        "4. Revisa también clasificación, advertencias, referencias y estado antes de ejecutar código en BigQuery/Workbench.",
        "",
        "## Estado por lote",
        "",
        "| Lote | Operación | Región | Recursos | Completados | Pendientes | Advertencias | Estado | Digest |",
        "|---|---|---|---:|---:|---:|---:|---|---|",
    ]
    for lot in report.get("lots") or []:
        lines.append(
            f"| `{_md(lot.get('lot'))}` | `{_md(lot.get('operation') or report.get('operation') or 'copy')}` | `{_md(lot.get('location') or '-')}` | {lot.get('resource_count', 0)} | {lot.get('completed_count', lot.get('published_count', 0))} | {lot.get('pending_count', 0)} | {lot.get('warning_count', 0)} | `{_md(lot.get('status'))}` | `{_md(lot.get('publication_digest'))}` |"
        )
    lines.extend(
        [
            "",
            "## Índice de recursos",
            "",
            "| # | Lote | Tipo | Recurso | Estado | Clase | Cambios | Reemplazos textuales | Incidentes no encontrados | Destino | Diff |",
            "|---:|---|---|---|---|---|---:|---:|---:|---|---|",
        ]
    )
    for index, item in enumerate(resources, 1):
        diff = f"[Abrir diff]({_md(item.get('review_relative'))})" if item.get("review_relative") else "-"
        lines.append(
            f"| {index} | `{_md(item.get('lot'))}` | `{_md(item.get('kind'))}` | `{_md(item.get('display_name'))}` | `{_md(item.get('status'))}` | `{_md((item.get('classification') or {}).get('statement_class'))}` | {len(item.get('changed_files') or [])} | {item.get('route_replacement_occurrence_count', 0)} | {item.get('unmatched_route_count', 0)} | `{_md(item.get('destination_display_name'))}` | {diff} |"
        )

    lines.extend(["", "## Rutas reemplazadas (consolidado)", ""])
    replacements = report.get("route_replacements") or []
    if replacements:
        lines.extend(
            [
                "| ID | Ruta original | Ruta nueva | Ocurrencias | Recursos |",
                "|---|---|---|---:|---|",
            ]
        )
        for item in replacements:
            lines.append(
                f"| `{_md(item.get('mapping_id'))}` | `{_md(item.get('old'))}` | `{_md(item.get('new'))}` | {item.get('occurrences', 0)} | {_md(', '.join(item.get('resources') or []))} |"
            )
    else:
        lines.append("No se reemplazaron rutas en la campaña.")

    lines.extend(["", "## Incidentes de ruta no encontrada / no cubierta (consolidado)", ""])
    unmatched = report.get("unmatched_routes") or []
    if unmatched:
        lines.extend(
            [
                "Cada fila representa un incidente único por recurso y cadena de ruta que permaneció sin cambios porque no tuvo coincidencia en el diccionario. Si la misma cadena aparece varias veces dentro de un recurso, el detector la registra una sola vez y conserva su primera posición.",
                "",
                "| Lote | Recurso | Ruta | Archivo/celda | Línea | Posición |",
                "|---|---|---|---|---:|---:|",
            ]
        )
        for item in unmatched:
            path = str(item.get("path") or "-")
            if item.get("cell") is not None:
                path += f" · celda {item['cell']}"
            position = "-"
            if item.get("start") is not None or item.get("end") is not None:
                position = f"{item.get('start', '-')}–{item.get('end', '-')}"
            lines.append(
                f"| `{_md(item.get('lot'))}` | `{_md(item.get('resource'))}` | `{_md(item.get('route'))}` | `{_md(path)}` | {_md(item.get('line') or '-')} | {_md(position)} |"
            )
    else:
        lines.append("No hubo rutas no encontradas en la campaña.")

    no_route = [item for item in resources if not item.get("route_replacement_group_count")]
    lines.extend(["", "## Recursos sin reemplazos de ruta", ""])
    if no_route:
        lines.append("Estos recursos no tuvieron coincidencias del diccionario. Si contenían referencias del proyecto origen, quedaron sin cambios y aparecen como incidentes arriba.")
        lines.append("")
        lines.append("| Lote | Tipo | Recurso | Incidentes no encontrados | Estado | Diff |")
        lines.append("|---|---|---|---:|---|---|")
        for item in no_route:
            diff = f"[Abrir diff]({_md(item.get('review_relative'))})" if item.get("review_relative") else "-"
            lines.append(
                f"| `{_md(item.get('lot'))}` | `{_md(item.get('kind'))}` | `{_md(item.get('display_name'))}` | {item.get('unmatched_route_count', 0)} | `{_md(item.get('status'))}` | {diff} |"
            )
    else:
        lines.append("Todos los recursos tuvieron al menos una coincidencia de ruta.")

    lines.extend(["", "## Detalle por recurso", ""])
    for index, item in enumerate(resources, 1):
        classification = item.get("classification") or {}
        review = item.get("review") or {}
        lines.extend(
            [
                "<details>",
                f"<summary>{index}. <code>{_md(item.get('display_name'))}</code> · { _md(item.get('kind')) } · estado <code>{_md(item.get('status'))}</code></summary>",
                "",
                f"- Lote: `{_md(item.get('lot'))}` · ordinal: `{item.get('ordinal', '-')}`",
                f"- Recurso origen: `{_md(item.get('source_name'))}`",
                f"- Archivo: `{_md(item.get('source_filename'))}` · archivos/celdas modificados: `{len(item.get('changed_files') or [])}`",
                f"- Destino: `{_md(item.get('destination_project'))}` / `{_md(item.get('destination_repository_id'))}` · nombre visible `{_md(item.get('destination_display_name'))}`",
                f"- Estado: **{_md(item.get('status'))}** · elegible para migración: `{item.get('migration_eligible')}` · ejecución habilitada: `{item.get('execution_eligible')}`",
                f"- Clasificación: `{_md(classification.get('statement_class'))}` · lectura estática: `{classification.get('read_only')}` · revisión requerida: `{review.get('required')}`",
            ]
        )
        if item.get("runtime_error"):
            lines.append(f"- Incidencia durante el intento de publicación: **{_md(item.get('runtime_error'))}**")
        if item.get("destination_repository"):
            lines.append(f"- Repositorio publicado: `{_md(item.get('destination_repository'))}` · commit `{_md(item.get('published_commit_sha'))}`")
        if item.get("review_relative"):
            lines.append(f"- **Diff:** [Abrir diff]({_md(item.get('review_relative'))})")
        lines.extend(
            [
                "",
                "### Rutas reemplazadas",
                "",
                *_render_route_table(item.get("route_replacements") or []),
                "### Incidentes de ruta no encontrada / no cubierta",
                "",
                *_render_route_table(item.get("unmatched_routes") or [], unmatched=True),
                "### Archivos o celdas modificados",
                "",
            ]
        )
        lines.extend(f"- `{_md(path)}`" for path in _list_or_none(item.get("changed_files") or [], "Ninguno"))
        lines.extend(["", "### Advertencias y bloqueos", ""])
        if item.get("warnings"):
            lines.append("| Tipo | Archivo/celda | Línea | Detalle |")
            lines.append("|---|---|---:|---|")
            for warning in item["warnings"]:
                path = str(warning.get("path") or "-")
                if warning.get("cell") is not None:
                    path += f" · celda {warning['cell']}"
                detail = warning.get("route") or warning.get("rule") or warning.get("statement_class") or "-"
                lines.append(f"| `{_md(warning.get('kind'))}` | `{_md(path)}` | {_md(warning.get('line') or '-')} | `{_md(detail)}` |")
        else:
            lines.append("Sin advertencias registradas.")
        if item.get("blockers"):
            lines.extend(["", "Bloqueos:"])
            lines.extend(f"- `{_md(blocker.get('kind'))}` en `{_md(blocker.get('path') or '-')}`" for blocker in item["blockers"])
        lines.extend(
            [
                "",
                "### Referencias y trazabilidad",
                "",
                f"- Referencias detectadas: `{_md(', '.join(classification.get('references') or []) or 'ninguna')}`",
                f"- Antes: `{_md(item.get('before_sha256'))}`",
                f"- Propuesto: `{_md(item.get('proposed_sha256'))}`",
                f"- Origen (hash): `{_md(item.get('source_content_sha256'))}` · head `{_md(item.get('source_head_commit'))}`",
                f"- Tarea (referencia relativa): `{_md(item.get('task_relative') or 'omitida')}`",
                f"- Auditoría: tarea `{_md((item.get('audit') or {}).get('task_id') or '-')}` · archivado `{_md((item.get('audit') or {}).get('archived_at') or '-')}`",
                "",
                "</details>",
                "",
            ]
        )
    return "\n".join(lines)


def _html_resource_id(item: Mapping[str, Any]) -> str:
    """Return a stable, HTML-safe identifier for a resource detail."""
    value = "|".join(
        str(item.get(key) or "")
        for key in ("lot", "ordinal", "kind", "source_name", "display_name")
    )
    return "resource-" + hashlib.sha256(value.encode("utf-8")).hexdigest()[:16]


def _safe_relative_task(campaign_root: Path, item: Mapping[str, Any]) -> Path:
    raw_task = str(item.get("task") or "").strip()
    resource_name = item.get("display_name") or item.get("source_name") or "<sin nombre>"
    if not raw_task:
        raise BatchError(f"El recurso {resource_name} no tiene task")
    task = Path(raw_task).expanduser().resolve()
    root = campaign_root.resolve()
    if root not in task.parents or not task.is_dir():
        raise BatchError(
            f"El task de {resource_name} está fuera de la campaña o no existe: {task}"
        )
    return task


def _diff_file_payload(file: Mapping[str, Any], *, context_lines: int) -> dict[str, Any]:
    """Project a review file into compact, renderable diff hunks."""
    before = str(file.get("before") or "")
    after = str(file.get("after") or "")
    before_lines = before.splitlines()
    after_lines = after.splitlines()
    newline_only = bool(file.get("changed")) and before != after and before_lines == after_lines
    matcher = difflib.SequenceMatcher(None, before_lines, after_lines, autojunk=False)
    groups = matcher.get_grouped_opcodes(max(0, min(int(context_lines), 20)))
    hunks: list[dict[str, Any]] = []
    for group in groups:
        first = group[0]
        last = group[-1]
        old_start = int(first[1])
        old_end = int(last[2])
        new_start = int(first[3])
        new_end = int(last[4])
        rows: list[dict[str, Any]] = []
        for tag, old_begin, old_finish, new_begin, new_finish in group:
            if tag == "equal":
                for offset in range(old_finish - old_begin):
                    rows.append(
                        {
                            "kind": "context",
                            "old_line": old_begin + offset + 1,
                            "new_line": new_begin + offset + 1,
                            "text": before_lines[old_begin + offset],
                        }
                    )
            elif tag in {"delete", "replace"}:
                for offset in range(old_finish - old_begin):
                    rows.append(
                        {
                            "kind": "removed",
                            "old_line": old_begin + offset + 1,
                            "new_line": None,
                            "text": before_lines[old_begin + offset],
                        }
                    )
            if tag in {"insert", "replace"}:
                for offset in range(new_finish - new_begin):
                    rows.append(
                        {
                            "kind": "added",
                            "old_line": None,
                            "new_line": new_begin + offset + 1,
                            "text": after_lines[new_begin + offset],
                        }
                    )
        hunks.append(
            {
                "old_start": old_start + 1 if old_end > old_start else old_start,
                "old_count": old_end - old_start,
                "new_start": new_start + 1 if new_end > new_start else new_start,
                "new_count": new_end - new_start,
                "rows": rows,
            }
        )
    return {
        "path": str(file.get("path") or ""),
        "label": str(file.get("label") or file.get("path") or ""),
        "language": str(file.get("language") or ""),
        "added": _as_int(file.get("added")),
        "removed": _as_int(file.get("removed")),
        "changed": bool(file.get("changed")),
        "newline_only": newline_only,
        "hunks": hunks,
    }


def build_embedded_diff_index(
    report: Mapping[str, Any],
    campaign_root: Path,
    *,
    context_lines: int = 3,
) -> dict[str, Any]:
    """Build a bounded diff payload for every resource in a campaign.

    Only changed lines and bounded context are returned.  The row-free JSON
    report remains unchanged.  Baseline/proposal hashes are checked before a
    diff is accepted; old notebook tasks with serialization-only differences
    are accepted with an explicit status.
    """
    if int(context_lines) < 0 or int(context_lines) > 20:
        raise BatchError("context_lines debe estar entre 0 y 20")
    campaign_root = Path(campaign_root).expanduser().resolve()
    resources: dict[str, dict[str, Any]] = {}
    changed_file_count = 0
    diff_row_count = 0
    for item in report.get("resources") or []:
        if not isinstance(item, Mapping):
            raise BatchError("El reporte contiene un recurso inválido")
        resource_name = str(item.get("display_name") or item.get("source_name") or "<sin nombre>")
        resource_id = _html_resource_id(item)
        if resource_id in resources:
            raise BatchError(f"Identificador duplicado para el recurso {resource_name}")
        # Inventory manifests intentionally include resources that were not
        # prepared (for example destination conflicts, empty content, or
        # security-pending notebooks).  They still belong in the analyst
        # report, but there is no task workspace from which a diff can be
        # reconstructed.  Keep a transparent placeholder instead of making
        # the complete report fail for the first such resource.
        if not str(item.get("task") or "").strip():
            resources[resource_id] = {
                "resource_id": resource_id,
                "hash_status": "not_prepared",
                "observed_before_sha256": "",
                "observed_after_sha256": "",
                "files": [],
            }
            continue
        # Sealed-copy tasks deliberately contain only a redacted workspace.
        # The batch record retains hashes and coordinates, but embedding a
        # code diff here could accidentally expose a secret or a nearby
        # credential.  The per-task review.html remains the approved,
        # redacted review surface, so the campaign report advertises the
        # omission rather than attempting to compare raw bytes.
        if bool(item.get("sealed_copy")) or str((item.get("security") or {}).get("secret_handling") or "") == "sealed_copy":
            resources[resource_id] = {
                "resource_id": resource_id,
                "hash_status": "sealed_redacted",
                "observed_before_sha256": "",
                "observed_after_sha256": "",
                "files": [],
                "redacted": True,
            }
            continue
        task = _safe_relative_task(campaign_root, item)
        try:
            manifest = read_manifest(task)
            filename = str(manifest.get("filename") or item.get("source_filename") or "")
            if not filename or Path(filename).is_absolute() or ".." in Path(filename).parts:
                raise TaskError("filename inválido en el task")
            before = baseline_file(task, filename)
            kind = str(item.get("kind") or (manifest.get("resource") or {}).get("kind") or "")
            after = preview_notebook_task(task) if kind == "notebook" else (task / filename).read_bytes()
            model = build_review_model(manifest, {}, before, after)
        except (OSError, NotebookError, TaskError, WorkspaceError, ValueError) as error:
            raise BatchError(f"No se pudo leer el task de {resource_name}: {error}") from error

        actual_before = hashlib.sha256(before).hexdigest()
        expected_before = str(item.get("before_sha256") or item.get("source_content_sha256") or "")
        if not expected_before:
            raise BatchError(f"Falta el hash baseline verificable para {resource_name}")
        if actual_before != expected_before:
            raise BatchError(f"El baseline no coincide para {resource_name}")
        actual_after = hashlib.sha256(after).hexdigest()
        expected_after = str(item.get("proposed_sha256") or "")
        if not expected_after:
            raise BatchError(f"Falta el hash de propuesta verificable para {resource_name}")
        file_payloads = [
            _diff_file_payload(file, context_lines=context_lines)
            for file in (model.get("files") or [])
        ]
        content_changed = any(file.get("changed") for file in file_payloads)
        hash_status = "match"
        if actual_after != expected_after:
            # Older notebook batches recorded the original JSON hash while the
            # review renderer compared reconstructed cells.
            if kind == "notebook" and not content_changed:
                hash_status = "notebook_serialization_normalized"
            else:
                raise BatchError(f"La propuesta no coincide para {resource_name}")
        changed_file_count += sum(1 for file in file_payloads if file.get("changed"))
        diff_row_count += sum(
            len(hunk.get("rows") or [])
            for file in file_payloads
            for hunk in (file.get("hunks") or [])
        )
        resources[resource_id] = {
            "resource_id": resource_id,
            "hash_status": hash_status,
            "observed_before_sha256": actual_before,
            "observed_after_sha256": actual_after,
            "files": file_payloads,
        }
    return {
        "schema_version": DIFF_PAYLOAD_SCHEMA_VERSION,
        "context_lines": int(context_lines),
        "resource_count": len(resources),
        "changed_file_count": changed_file_count,
        "diff_row_count": diff_row_count,
        "resources": resources,
    }


def _html_resource_projection(item: Mapping[str, Any]) -> dict[str, Any]:
    """Return report metadata safe to embed without machine-local paths."""
    removed = {"manifest", "task", "review_file", "review_relative"}
    clean = {key: value for key, value in item.items() if key not in removed}
    clean["resource_id"] = _html_resource_id(item)
    audit = clean.get("audit")
    if isinstance(audit, Mapping):
        audit_copy = dict(audit)
        audit_copy["files"] = [
            Path(str(value)).name for value in (audit.get("files") or [])
        ]
        clean["audit"] = audit_copy
    return clean


def _html_public_report(report: Mapping[str, Any], diff_index: Mapping[str, Any]) -> dict[str, Any]:
    """Project report metadata and the diff payload into one HTML model."""
    top_keys = (
        "schema_version", "source_schema_version", "campaign_id", "generated_at",
        "operation", "locations", "source_project", "destination_project", "location", "resource_count",
        "published_count", "completed_count", "pending_count", "status_counts", "kind_counts",
        "classification_counts", "warning_counts", "review_reason_counts",
        "review_required_count", "execution_eligible_count", "changed_file_count",
        "route_replacement_group_count", "route_replacement_occurrence_count",
        "unique_route_replacement_group_count", "unmatched_route_count",
        "unique_unmatched_route_count", "route_replacement_group_count_definition",
        "unmatched_route_count_definition", "pending_resources", "sources",
        "scope_description", "excluded_resource_count", "excluded_resources",
    )
    public: dict[str, Any] = {
        key: report.get(key) for key in top_keys if key in report
    }
    public["lots"] = [
        {
            key: lot.get(key)
            for key in (
                "lot", "campaign_id", "operation", "location", "status", "resource_count", "published_count",
                "completed_count", "pending_count", "warning_count", "publication_digest",
            )
            if key in lot
        }
        for lot in (report.get("lots") or [])
        if isinstance(lot, Mapping)
    ]
    public["resources"] = [
        _html_resource_projection(item)
        for item in (report.get("resources") or [])
        if isinstance(item, Mapping)
    ]
    public["diff_index"] = diff_index
    return public


def _html_json(value: Any) -> str:
    return (
        json.dumps(value, ensure_ascii=False, separators=(",", ":"))
        .replace("<", "\\u003c")
        .replace(">", "\\u003e")
        .replace("&", "\\u0026")
    )


def _html_static_index(report: Mapping[str, Any]) -> str:
    rows: list[str] = []
    for item in report.get("resources") or []:
        if not isinstance(item, Mapping):
            continue
        resource_id = _html_resource_id(item)
        rows.append(
            "<tr>"
            f"<td><a href=\"#resource={html.escape(resource_id, quote=True)}\">"
            f"{html.escape(str(item.get('display_name') or '-'))}</a></td>"
            f"<td>{html.escape(str(item.get('kind') or '-'))}</td>"
            f"<td>{html.escape(str(item.get('status') or '-'))}</td>"
            f"<td>{_as_int(item.get('route_replacement_occurrence_count'))}</td>"
            f"<td>{_as_int(item.get('unmatched_route_count'))}</td>"
            "</tr>"
        )
    return (
        '<noscript><section class="noscript"><h2>Índice sin JavaScript</h2>'
        '<p>El navegador no ejecutó la interfaz interactiva. Este índice conserva el acceso a cada recurso.</p>'
        '<div class="table-scroll"><table><thead><tr><th>Recurso</th><th>Tipo</th>'
        '<th>Estado</th><th>Reemplazos</th><th>Incidencias</th></tr></thead>'
        f"<tbody>{''.join(rows)}</tbody></table></div></section></noscript>"
    )


def _html_excluded_resources(report: Mapping[str, Any]) -> str:
    """Render a compact inventory of resources outside the campaign."""
    excluded_labels = {"not_selected": "No seleccionado", "unsupported": "No soportado"}
    values = [value for value in (report.get("excluded_resources") or []) if isinstance(value, Mapping)]
    if not values:
        return ""
    rows = []
    for value in values:
        rows.append(
            "<tr>"
            f"<td class=\"mono\">{html.escape(str(value.get('routine_id') or '-'))}</td>"
            f"<td>{html.escape(excluded_labels.get(str(value.get('status') or ''), str(value.get('status') or '-')))}</td>"
            f"<td>{html.escape(str(value.get('reason') or '-'))}</td>"
            f"<td class=\"mono\">{html.escape(str(value.get('dataset') or '-'))}</td>"
            f"<td class=\"mono\">{html.escape(str(value.get('source_name') or '-'))}</td>"
            "</tr>"
        )
    return (
        '<details class="coverage"><summary>Recursos fuera de la campaña '
        f"({_as_int(report.get('excluded_resource_count'))})</summary>"
        '<p>Se muestran para no perder cobertura del inventario; no tienen propuesta ni diff porque no fueron migrados en esta campaña.</p>'
        '<div class="table-scroll"><table><thead><tr><th>Rutina</th><th>Estado</th><th>Motivo</th><th>Dataset</th><th>Recurso origen</th></tr></thead>'
        f"<tbody>{''.join(rows)}</tbody></table></div></details>"
    )


def render_detailed_html(report: Mapping[str, Any], diff_index: Mapping[str, Any]) -> str:
    """Render an offline, read-only analyst report with embedded diffs."""
    public = _html_public_report(report, diff_index)
    payload = _html_json(public)
    title = html.escape(
        f"QueryFlow · revisión de migración · {report.get('campaign_id') or ''}"
    )
    campaign = html.escape(str(report.get("campaign_id") or "Campaña de migración"))
    source = html.escape(str(report.get("source_project") or "—"))
    destination = html.escape(str(report.get("destination_project") or "—"))
    location = html.escape(str(report.get("location") or "—"))
    operation = html.escape(str(report.get("operation") or "copy"))
    generated = html.escape(str(report.get("generated_at") or "—"))
    scope_description = html.escape(str(report.get("scope_description") or "Guía autocontenida para revisión humana."))
    source_summary = " · ".join(
        f"{html.escape(str(source.get('label') or source.get('campaign_id') or 'Campaña'))}: {_as_int(source.get('resource_count')):,}"
        for source in (report.get("sources") or [])
        if isinstance(source, Mapping)
    )
    source_summary_html = f' <span class="mono">{source_summary}</span>' if source_summary else ""
    excluded_summary = _as_int(report.get("excluded_resource_count"))
    excluded_summary_html = (
        f' <span class="coverage-note">{excluded_summary:,} rutina(s) quedaron fuera del alcance; abre el inventario para ver el motivo.</span>'
        if excluded_summary
        else ""
    )
    static_index = _html_static_index(report)
    excluded_html = _html_excluded_resources(report)
    css = """
:root { color-scheme: dark; --bg:#0b1020; --surface:#121a2b; --surface-2:#1b263b; --surface-3:#22314a; --text:#eef4ff; --muted:#a8b7ce; --faint:#7f91ad; --border:#30415e; --accent:#71b7ff; --good:#5ee6a8; --good-bg:#123b30; --bad:#ff879d; --bad-bg:#482331; --warn:#ffd166; --warn-bg:#453615; }
* { box-sizing:border-box; } html { scroll-behavior:smooth; }
body { margin:0; background:var(--bg); color:var(--text); font:15px/1.5 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif; }
button,input,select { font:inherit; } button,a,input,select { touch-action:manipulation; } a { color:var(--accent); }
.skip-link { position:absolute; left:12px; top:-48px; z-index:30; padding:10px 14px; border-radius:8px; background:var(--accent); color:#07111f; font-weight:700; } .skip-link:focus { top:12px; }
.app-header { border-bottom:1px solid var(--border); background:var(--surface); } .header-inner,main { width:min(1480px,100%); margin:0 auto; } .header-inner { padding:24px clamp(16px,4vw,48px) 20px; }
.eyebrow { color:var(--faint); font-size:.75rem; letter-spacing:.08em; text-transform:uppercase; } .hero { display:flex; align-items:flex-start; justify-content:space-between; gap:20px; margin-top:7px; } h1 { margin:0; font-size:clamp(1.4rem,3vw,2.2rem); letter-spacing:-.035em; } .meta { margin-top:5px; color:var(--muted); font:.82rem ui-monospace,SFMono-Regular,Consolas,monospace; overflow-wrap:anywhere; }
 .internal-note { margin:14px 0 0; padding:9px 11px; border:1px solid #6d5320; border-radius:8px; background:var(--warn-bg); color:#ffe4a3; font-size:.86rem; }
 .scope-note { margin:10px 0 0; color:var(--muted); font-size:.84rem; } .scope-note strong { color:var(--text); } .scope-note .mono { color:var(--accent); } .coverage-note { color:var(--warn); }
.metrics { display:grid; grid-template-columns:repeat(5,minmax(0,1fr)); gap:8px; margin-top:18px; } .metric { min-height:66px; padding:10px 12px; border:1px solid var(--border); border-radius:9px; background:var(--surface-2); } .metric span { display:block; color:var(--faint); font-size:.7rem; letter-spacing:.06em; text-transform:uppercase; } .metric strong { display:block; margin-top:2px; font:600 1.12rem ui-monospace,SFMono-Regular,Consolas,monospace; }
main { padding:20px clamp(16px,4vw,48px) 60px; } .toolbar { position:sticky; top:0; z-index:10; display:grid; grid-template-columns:minmax(220px,2fr) repeat(5,minmax(120px,1fr)) auto; gap:8px; align-items:end; margin-bottom:14px; padding:10px; border:1px solid var(--border); border-radius:10px; background:color-mix(in srgb,var(--surface) 96%,transparent); backdrop-filter:blur(10px); }
.field { display:flex; min-width:0; flex-direction:column; gap:4px; } .field label { color:var(--faint); font-size:.72rem; } input,select,.button { min-height:42px; border:1px solid var(--border); border-radius:8px; background:var(--surface-2); color:var(--text); } input,select { width:100%; padding:8px 10px; } .button { padding:8px 12px; cursor:pointer; } .button:hover { border-color:var(--accent); background:var(--surface-3); } .button:focus-visible,input:focus-visible,select:focus-visible,a:focus-visible { outline:3px solid color-mix(in srgb,var(--accent) 65%,transparent); outline-offset:2px; } .toolbar-status { grid-column:1 / -1; color:var(--muted); font-size:.82rem; }
.layout { display:grid; grid-template-columns:minmax(390px,.9fr) minmax(0,1.5fr); gap:14px; align-items:start; } .panel { overflow:hidden; border:1px solid var(--border); border-radius:10px; background:var(--surface); } .panel-heading { display:flex; align-items:center; justify-content:space-between; gap:10px; padding:12px 14px; border-bottom:1px solid var(--border); background:var(--surface-2); } .panel-heading h2 { margin:0; font-size:1rem; } .table-scroll { overflow:auto; }
table { width:100%; border-collapse:collapse; } th,td { padding:9px 10px; border-bottom:1px solid var(--border); text-align:left; vertical-align:top; } th { color:var(--faint); font-size:.7rem; letter-spacing:.05em; text-transform:uppercase; } th button { padding:0; border:0; background:none; color:inherit; cursor:pointer; font:inherit; letter-spacing:inherit; text-transform:inherit; } th button:hover { color:var(--accent); } tbody tr:last-child td { border-bottom:0; }
.resource-row { width:100%; padding:0; border:0; background:none; color:var(--text); cursor:pointer; text-align:left; } .resource-row strong,.resource-row small { display:block; overflow-wrap:anywhere; } .resource-row small { margin-top:2px; color:var(--faint); font:.72rem ui-monospace,SFMono-Regular,Consolas,monospace; } tr.selected td { background:#203556; }
 .badge { display:inline-flex; align-items:center; gap:5px; padding:3px 7px; border:1px solid var(--border); border-radius:999px; font-size:.72rem; white-space:nowrap; } .badge.good { color:var(--good); border-color:#2f8b68; } .badge.bad { color:var(--bad); border-color:#a14a60; } .badge.warn { color:var(--warn); border-color:#927332; } .mono { font:.76rem ui-monospace,SFMono-Regular,Consolas,monospace; } .empty { padding:24px 16px; color:var(--muted); text-align:center; }
 .incident-list { margin:8px 0 0; padding-left:18px; color:var(--muted); } .incident-list li + li { margin-top:4px; } .incident-list code { color:var(--text); }
.detail { min-height:420px; } .detail-content { padding:16px; } .detail-title { display:flex; align-items:flex-start; justify-content:space-between; gap:12px; } .detail-title h2 { margin:0; font-size:1.2rem; overflow-wrap:anywhere; } .detail-subtitle { margin:3px 0 0; color:var(--muted); font-size:.84rem; } .detail-grid { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:8px; margin:14px 0; } .fact { padding:9px 10px; border:1px solid var(--border); border-radius:8px; background:var(--surface-2); } .fact dt { color:var(--faint); font-size:.7rem; text-transform:uppercase; } .fact dd { margin:2px 0 0; overflow-wrap:anywhere; }
.callout { margin:12px 0; padding:10px 12px; border-left:3px solid var(--accent); background:var(--surface-2); color:var(--muted); } .callout.warn { border-color:var(--warn); } .callout.bad { border-color:var(--bad); background:var(--bad-bg); color:#ffd2dc; } .detail-section { margin-top:16px; } .detail-section h3 { margin:0 0 7px; font-size:.9rem; } .detail-section table { font-size:.82rem; } .detail-section th,.detail-section td { padding:7px 8px; } .route-old { color:var(--bad); } .route-new { color:var(--good); }
.diff-file { margin-top:10px; overflow:hidden; border:1px solid var(--border); border-radius:8px; } .diff-file header { display:flex; justify-content:space-between; gap:10px; padding:9px 10px; background:var(--surface-2); } .diff-file header strong,.diff-file header small { display:block; } .diff-file header small { color:var(--faint); font:.72rem ui-monospace,SFMono-Regular,Consolas,monospace; } .diff-count { white-space:nowrap; font:.74rem ui-monospace,SFMono-Regular,Consolas,monospace; } .diff-add { color:var(--good); } .diff-remove { color:var(--bad); } .hunk { border-top:1px solid var(--border); } .hunk:first-child { border-top:0; } .hunk-head { padding:5px 9px; background:#172b48; color:#9ccaff; font:.72rem ui-monospace,SFMono-Regular,Consolas,monospace; }
table.diff { table-layout:fixed; font:.78rem/1.5 ui-monospace,SFMono-Regular,Consolas,monospace; } table.diff td { white-space:pre-wrap; overflow-wrap:anywhere; } table.diff .line-no { width:52px; color:var(--faint); text-align:right; user-select:none; } table.diff .mark { width:24px; text-align:center; color:var(--faint); } table.diff tr.context td { background:var(--surface); } table.diff tr.added td { background:var(--good-bg); } table.diff tr.removed td { background:var(--bad-bg); }
details { margin-top:12px; border:1px solid var(--border); border-radius:8px; background:var(--surface-2); } summary { padding:9px 10px; cursor:pointer; color:var(--muted); } .coverage { margin:0 0 14px; } .coverage p { margin:0; padding:9px 10px 0; color:var(--muted); font-size:.82rem; } pre { margin:0; padding:10px; overflow:auto; border-top:1px solid var(--border); color:var(--faint); font:.72rem/1.5 ui-monospace,SFMono-Regular,Consolas,monospace; } .noscript { margin-top:14px; padding:14px; border:1px solid var(--border); border-radius:10px; background:var(--surface); } .noscript h2 { margin:0 0 4px; font-size:1rem; } .noscript p { color:var(--muted); } .sr-only { position:absolute; width:1px; height:1px; padding:0; margin:-1px; overflow:hidden; clip:rect(0,0,0,0); white-space:nowrap; border:0; }
@media (max-width:1100px) { .toolbar { grid-template-columns:repeat(3,minmax(140px,1fr)); } .layout { grid-template-columns:1fr; } .detail { min-height:0; } } @media (max-width:680px) { .hero { display:block; } .metrics { grid-template-columns:repeat(2,minmax(0,1fr)); } .metrics .metric:last-child { grid-column:1/-1; } .toolbar { grid-template-columns:1fr 1fr; } .toolbar .field:first-child,.toolbar-status { grid-column:1/-1; } .detail-grid { grid-template-columns:1fr; } .layout { display:block; } .panel + .panel { margin-top:14px; } } @media (prefers-reduced-motion:reduce) { *,*::before,*::after { scroll-behavior:auto !important; transition-duration:.01ms !important; animation-duration:.01ms !important; } }
"""
    script = r"""
const payload = JSON.parse(document.getElementById('queryflow-payload').textContent);
const resources = payload.resources || [];
const diffResources = (payload.diff_index || {}).resources || {};
const STATUS_LABELS = {
  published:'Publicado', published_verified:'Publicado y verificado',
  already_present_identical:'Ya existía · idéntico', already_compliant:'Ya cumple rutas',
  ready_to_update:'Listo para actualizar', prepared:'Preparado para publicar',
  security_pending:'Pendiente de seguridad', pending:'Pendiente de revisión',
  blocked:'Bloqueado', failed:'Falló la publicación', destination_conflict:'Conflicto de destino'
};
const state = { query:'', kind:'all', status:'all', classification:'all', lot:'all', issue:'all', sort:'attention', selected:'' };
const $ = (id) => document.getElementById(id);
const esc = (value) => String(value ?? '').replace(/[&<>'"]/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number = (value) => Number(value || 0).toLocaleString('es-CO');
const unique = (values) => [...new Set(values.filter(Boolean))].sort((a,b) => String(a).localeCompare(String(b),'es'));
const statusLabel = (value) => STATUS_LABELS[value] || value || 'Sin estado';
const statusTone = (value) => ['published','published_verified','already_present_identical','already_compliant'].includes(value) ? 'good' : ['failed'].includes(value) ? 'bad' : 'warn';
const routes = (item) => [...(item.route_replacements || []).map((x) => x.old), ...(item.route_replacements || []).map((x) => x.new), ...(item.unmatched_routes || []).map((x) => x.route)];
const issue = (item) => item.unmatched_route_count > 0 ? 'unknown_route' : (item.blockers || []).length ? 'blocker' : item.runtime_error ? 'execution_error' : (item.warnings || []).length ? 'warning' : 'none';
const issueLabel = { unknown_route:'Rutas no cubiertas', blocker:'Bloqueos', execution_error:'Fallo de publicación', warning:'Otras advertencias', none:'Sin incidencias' };
function fillSelect(id, values, label, labels={}) { const select=$(id); select.innerHTML=`<option value="all">${esc(label)}</option>`+values.map((value)=>`<option value="${esc(value)}">${esc(labels[value]||value)}</option>`).join(''); }
fillSelect('filter-kind',unique(resources.map((x)=>x.kind)),'Todos los tipos'); fillSelect('filter-status',unique(resources.map((x)=>x.status)),'Todos los estados',STATUS_LABELS); fillSelect('filter-classification',unique(resources.map((x)=>(x.classification||{}).statement_class)),'Todas las clases'); fillSelect('filter-lot',unique(resources.map((x)=>x.lot)),'Todos los lotes');
function matches(item) { const q=state.query.trim().toLocaleLowerCase('es'); const incidentText=[...(item.warnings||[]),...(item.blockers||[])].flatMap((x)=>Object.values(x||{})); const text=[item.display_name,item.source_name,item.destination_display_name,item.destination_project,item.kind,item.lot,item.role,item.routine_type,item.language,...routes(item),...incidentText].join(' ').toLocaleLowerCase('es'); return (!q||text.includes(q))&&(state.kind==='all'||item.kind===state.kind)&&(state.status==='all'||item.status===state.status)&&(state.classification==='all'||(item.classification||{}).statement_class===state.classification)&&(state.lot==='all'||item.lot===state.lot)&&(state.issue==='all'||issue(item)===state.issue); }
function compare(a,b) { if(state.sort==='name') return String(a.display_name).localeCompare(String(b.display_name),'es'); if(state.sort==='incidents') return ((b.unmatched_route_count||0)-(a.unmatched_route_count||0))||((b.blockers||[]).length-(a.blockers||[]).length)||String(a.display_name).localeCompare(String(b.display_name),'es'); if(state.sort==='replacements') return (b.route_replacement_occurrence_count-a.route_replacement_occurrence_count)||String(a.display_name).localeCompare(String(b.display_name),'es'); const attention=(x)=>(['pending','blocked','destination_conflict','security_pending'].includes(x.status)?100000:0)+(['failed'].includes(x.status)?90000:0)+(['ready_to_update','prepared'].includes(x.status)?1000:0)+(x.unmatched_route_count||0)*100+((x.blockers||[]).length||0)*75+((x.warnings||[]).length||0); return attention(b)-attention(a)||String(a.display_name).localeCompare(String(b.display_name),'es'); }
function badge(value,tone) { return `<span class="badge ${tone||''}">${esc(value||'—')}</span>`; }
function updateSortHeaders() { document.querySelectorAll('[data-sort]').forEach((button)=>{ const active=button.dataset.sort===state.sort; button.parentElement.setAttribute('aria-sort',active?(state.sort==='name'?'ascending':'descending'):'none'); }); }
function renderRows() { const filtered=resources.filter(matches).sort(compare); $('result-count').textContent=`${number(filtered.length)} de ${number(resources.length)} recursos`; updateSortHeaders(); if(!filtered.length){ $('resource-rows').innerHTML='<tr><td colspan="6"><div class="empty">No hay recursos con estos filtros. Limpia la búsqueda o cambia los filtros.</div></td></tr>'; return; } $('resource-rows').innerHTML=filtered.map((item)=>{ const selected=item.resource_id===state.selected; const issueCount=(item.unmatched_route_count||0)+(item.blockers||[]).length+(item.runtime_error?1:0)+(item.warnings||[]).length; const issueTone=issue(item)==='none'?'good':issue(item)==='execution_error'?'bad':'warn'; return `<tr class="${selected?'selected':''}"><td><button class="resource-row" type="button" data-resource="${esc(item.resource_id)}"><strong>${esc(item.display_name||item.source_name)}</strong><small>${esc(item.kind)} · ${esc(item.lot||'')}</small></button></td><td>${badge(statusLabel(item.status),statusTone(item.status))}</td><td class="mono">${number(item.route_replacement_occurrence_count)}</td><td>${badge(number(issueCount),issueTone)}</td><td class="mono">${esc((item.classification||{}).statement_class||'—')}</td><td class="mono">${number((item.changed_files||[]).length)}</td></tr>`; }).join(''); document.querySelectorAll('[data-resource]').forEach((button)=>button.addEventListener('click',()=>selectResource(button.dataset.resource))); }
function routeTable(item) { const values=item.route_replacements||[]; if(!values.length)return '<p class="empty">No hubo coincidencias del diccionario en este recurso.</p>'; return `<div class="table-scroll"><table><thead><tr><th>ID</th><th>Ruta original</th><th>Ruta nueva</th><th>Ocurrencias</th></tr></thead><tbody>${values.map((route)=>`<tr><td class="mono">${esc(route.mapping_id)}</td><td class="route-old mono">${esc(route.old)}</td><td class="route-new mono">${esc(route.new)}</td><td class="mono">${number(route.occurrences)}</td></tr>`).join('')}</tbody></table></div>`; }
function unknownTable(item) { const values=item.unmatched_routes||[]; if(!values.length)return '<p class="empty">No se registraron rutas fuera del diccionario.</p>'; return `<div class="table-scroll"><table><thead><tr><th>Ruta</th><th>Archivo / celda</th><th>Línea</th><th>Posición</th></tr></thead><tbody>${values.map((route)=>{const path=`${route.path||'—'}${route.cell!=null?` · celda ${route.cell}`:''}`;const position=route.start!=null||route.end!=null?`${route.start??'—'}–${route.end??'—'}`:'—';return `<tr><td class="route-old mono">${esc(route.route)}</td><td class="mono">${esc(path)}</td><td class="mono">${esc(route.line??'—')}</td><td class="mono">${esc(position)}</td></tr>`;}).join('')}</tbody></table></div>`; }
function incidentList(values, fallback) { if(!values||!values.length)return `<p class="empty">${fallback}</p>`; return `<ul class="incident-list">${values.map((value)=>{const text=Object.entries(value||{}).filter(([key])=>!['start','end'].includes(key)).map(([key,val])=>`${key}: ${val}`).join(' · ');return `<li><code>${esc(text||'incidencia')}</code></li>`;}).join('')}</ul>`; }
function newlineNote(file) { return file.newline_only ? '<p class="callout">El cambio solo afecta el salto de línea final; no hay líneas de contenido distintas.</p>' : ''; }
function diffHtml(item) { const diff=diffResources[item.resource_id]; if(!diff)return '<div class="callout">No hay un diff preparado para este recurso.</div>'; if(diff.hash_status==='not_prepared')return '<div class="callout warn">No hay diff: este recurso no se preparó porque quedó pendiente, vacío o en conflicto con el destino. Revisa el estado y los bloqueos.</div>'; if(diff.hash_status==='sealed_redacted')return '<div class="callout warn">Diff omitido por seguridad: el recurso se preparó como copia sellada y el contenido no se embebe en este informe. Abre el preview redactado del task autorizado.</div>'; if(!(diff.files||[]).some((file)=>file.changed))return '<div class="callout">No hubo cambios de contenido para mostrar.</div>'; return (diff.files||[]).filter((file)=>file.changed).map((file)=>`<section class="diff-file"><header><div><strong>${esc(file.label)}</strong><small>${esc(file.path)} · ${esc(file.language)}</small></div><span class="diff-count"><span class="diff-add">+${number(file.added)}</span> <span class="diff-remove">−${number(file.removed)}</span></span></header>${newlineNote(file)}${(file.hunks||[]).map((hunk)=>`<div class="hunk"><div class="hunk-head">@@ -${hunk.old_start},${hunk.old_count} +${hunk.new_start},${hunk.new_count} @@</div><table class="diff"><tbody>${(hunk.rows||[]).map((row)=>`<tr class="${esc(row.kind)}"><td class="line-no">${esc(row.old_line??'')}</td><td class="line-no">${esc(row.new_line??'')}</td><td class="mark">${row.kind==='added'?'+':row.kind==='removed'?'−':' '}</td><td>${esc(row.text)}</td></tr>`).join('')}</tbody></table></div>`).join('')}</section>`).join(''); }
function detailHtml(item) { const reasons=(item.review||{}).reasons||[]; const warningText=(item.warnings||[]).map((warning)=>`${warning.kind||'advertencia'}${warning.path?` · ${warning.path}`:''}${warning.line?` · línea ${warning.line}`:''}`).join('; '); const diff=diffResources[item.resource_id]||{}; const hashNote=diff.hash_status==='notebook_serialization_normalized'?'<div class="callout warn">El notebook fue reconstruido para comparar celdas; la serialización JSON original y la propuesta observada tienen hashes distintos, pero no hay cambios de contenido.</div>':''; const summary=item.runtime_error?`La publicación no terminó: ${item.runtime_error}.`:item.blockers&&item.blockers.length?`El recurso quedó bloqueado y requiere una decisión humana antes de continuar.`:item.unmatched_route_count?`Se migró el recurso, pero ${number(item.unmatched_route_count)} ruta(s) quedaron sin coincidencia en el diccionario y requieren revisión manual.`:item.route_replacement_occurrence_count?`Se reemplazaron ${number(item.route_replacement_occurrence_count)} referencia(s) según el diccionario.`:'No se encontraron rutas del diccionario en este recurso.'; const summaryTone=item.runtime_error?'bad':item.blockers&&item.blockers.length?'warn':item.unmatched_route_count?'warn':''; const typeText=item.role?`${item.role}${item.routine_type?` · ${item.routine_type}`:''}`:(item.kind||'—'); const dependencyText=item.dependency_count?`${number(item.dependency_count)} detectada(s)${item.missing_dependency_count?` · ${number(item.missing_dependency_count)} no disponible(s)`:''}`:'—'; const issueCount=(item.unmatched_route_count||0)+(item.blockers||[]).length+(item.runtime_error?1:0)+(item.warnings||[]).length; return `<div class="detail-content"><div class="detail-title"><div><h2 id="detail-title">${esc(item.display_name||item.source_name)}</h2><p class="detail-subtitle">${esc(typeText)} · ${esc(item.lot||'')} · ${esc(statusLabel(item.status))}</p></div>${badge(statusLabel(item.status),statusTone(item.status))}</div>${hashNote}<dl class="detail-grid"><div class="fact"><dt>Origen</dt><dd class="mono">${esc(item.source_name||'—')}</dd></div><div class="fact"><dt>Destino</dt><dd class="mono">${esc(item.destination_project||'—')} / ${esc(item.destination_display_name||'—')}</dd></div><div class="fact"><dt>Tipo / lenguaje</dt><dd>${esc(typeText)} · ${esc(item.language||'—')}</dd></div><div class="fact"><dt>Dependencias</dt><dd>${esc(dependencyText)}</dd></div><div class="fact"><dt>Archivos o celdas modificados</dt><dd>${number((item.changed_files||[]).length)}</dd></div><div class="fact"><dt>Clasificación</dt><dd>${esc((item.classification||{}).statement_class||'—')}</dd></div><div class="fact"><dt>Reemplazos textuales</dt><dd>${number(item.route_replacement_occurrence_count)}</dd></div><div class="fact"><dt>Incidencias</dt><dd>${number(issueCount)}</dd></div></dl><section class="detail-section"><h3>Qué ocurrió</h3><p class="callout ${summaryTone}">${esc(summary)}${reasons.length?` Motivos de revisión: ${esc(reasons.join(', '))}.`:''}</p>${warningText?`<p class="callout warn">Advertencias: ${esc(warningText)}</p>`:''}${item.runtime_error?`<p class="callout bad">Error reportado por la publicación: ${esc(item.runtime_error)}</p>`:''}${item.blockers&&item.blockers.length?`<p class="callout warn"><strong>Bloqueos registrados</strong>${incidentList(item.blockers,'Sin detalle adicional.')}</p>`:''}</section><section class="detail-section"><h3>Rutas reemplazadas</h3>${routeTable(item)}</section><section class="detail-section"><h3>Rutas no cubiertas</h3>${unknownTable(item)}</section><section class="detail-section"><h3>Diff rojo / verde</h3>${diffHtml(item)}</section><details><summary>Ver trazabilidad técnica</summary><pre>${esc(JSON.stringify({status:item.status,status_label:statusLabel(item.status),before_sha256:item.before_sha256,proposed_sha256:item.proposed_sha256,source_content_sha256:item.source_content_sha256,source_head_commit:item.source_head_commit,published_commit_sha:item.published_commit_sha,audit:item.audit},null,2))}</pre></details></div>`; }
function selectResource(id,updateHash=true) { const item=resources.find((resource)=>resource.resource_id===id); if(!item)return; state.selected=id; if(updateHash)history.replaceState(null,'',`#resource=${encodeURIComponent(id)}`); $('detail').innerHTML=detailHtml(item); renderRows(); $('detail').focus({preventScroll:true}); }
function readHash() { const match=location.hash.match(/^#resource=(.*)$/); return match?decodeURIComponent(match[1]):''; }
['query','kind','status','classification','lot','issue'].forEach((name)=>{ const id=name==='query'?'search':`filter-${name}`; $(id).addEventListener(name==='query'?'input':'change',(event)=>{state[name]=event.target.value;renderRows();}); });
$('sort').addEventListener('change',(event)=>{state.sort=event.target.value;renderRows();}); $('clear').addEventListener('click',()=>{state.query='';state.kind='all';state.status='all';state.classification='all';state.lot='all';state.issue='all';$('search').value='';['kind','status','classification','lot','issue'].forEach((name)=>{$(`filter-${name}`).value='all';});renderRows();}); document.querySelectorAll('[data-sort]').forEach((button)=>button.addEventListener('click',()=>{$('sort').value=button.dataset.sort;state.sort=button.dataset.sort;renderRows();})); window.addEventListener('hashchange',()=>{const id=readHash();if(id)selectResource(id,false);}); renderRows(); const initial=readHash(); if(initial&&resources.some((item)=>item.resource_id===initial))selectResource(initial,false); else $('detail').innerHTML='<div class="empty">Selecciona un recurso para ver sus rutas, incidencias y diff.</div>';
"""
    metrics = (
        ("Recursos", report.get("resource_count", 0)),
        ("Migrados / verificados" if "completed_count" in report else "Publicados", report.get("completed_count", report.get("published_count", 0))),
        ("Pendientes / revisión", report.get("pending_count", 0)),
        ("Reemplazos", report.get("route_replacement_occurrence_count", 0)),
        ("Rutas no cubiertas", report.get("unmatched_route_count", 0)),
    )
    metric_html = "".join(
        f'<div class="metric"><span>{html.escape(label)}</span><strong>{_as_int(value):,}</strong></div>'
        for label, value in metrics
    )
    return f"""<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src data:; base-uri 'none'; form-action 'none'; connect-src 'none';"><title>{title}</title><style>{css}</style></head>
<body><a class="skip-link" href="#main-content">Saltar al contenido</a><header class="app-header"><div class="header-inner"><div class="eyebrow">QueryFlow · guía consolidada para revisión humana</div><div class="hero"><div><h1>Revisión de migración</h1><div class="meta">{campaign} · operación {operation} · {source} → {destination} · {location} · generado {generated}</div></div></div><p class="internal-note"><strong>Uso interno:</strong> este archivo contiene hunks de código para revisión. Compártelo únicamente por los canales autorizados.</p><p class="scope-note"><strong>Alcance:</strong> {scope_description}{source_summary_html}{excluded_summary_html}</p><div class="metrics">{metric_html}</div></div></header><main id="main-content" tabindex="-1"><section class="toolbar" aria-label="Filtros del informe"><div class="field"><label for="search">Buscar recursos</label><input id="search" type="search" placeholder="Nombre, destino o ruta…" autocomplete="off"></div><div class="field"><label for="filter-kind">Tipo</label><select id="filter-kind"></select></div><div class="field"><label for="filter-status">Estado</label><select id="filter-status"></select></div><div class="field"><label for="filter-classification">Clase SQL</label><select id="filter-classification"></select></div><div class="field"><label for="filter-lot">Lote</label><select id="filter-lot"></select></div><div class="field"><label for="filter-issue">Incidencias</label><select id="filter-issue"><option value="all">Todas</option><option value="unknown_route">Rutas no cubiertas</option><option value="blocker">Bloqueos</option><option value="execution_error">Fallo de publicación</option><option value="warning">Otras advertencias</option><option value="none">Sin incidencias</option></select></div><button id="clear" class="button" type="button">Limpiar</button><div class="toolbar-status"><span id="result-count" aria-live="polite"></span> · Ordenar por <select id="sort" style="width:auto;min-height:34px;padding:4px 7px"><option value="attention">atención</option><option value="name">nombre</option><option value="incidents">incidencias</option><option value="replacements">reemplazos</option></select></div></section>{excluded_html}<div class="layout"><section class="panel" aria-labelledby="list-title"><div class="panel-heading"><h2 id="list-title">Recursos</h2><span class="mono">{_as_int(report.get('resource_count')):,}</span></div><div class="table-scroll"><table><thead><tr><th scope="col"><button type="button" data-sort="name">Recurso</button></th><th scope="col">Estado</th><th scope="col"><button type="button" data-sort="replacements">Reemplazos</button></th><th scope="col"><button type="button" data-sort="incidents">Incidencias</button></th><th scope="col">Clase</th><th scope="col">Cambios</th></tr></thead><tbody id="resource-rows"></tbody></table></div></section><aside id="detail" class="panel detail" tabindex="-1" aria-label="Detalle del recurso"><div class="empty">Selecciona un recurso para ver sus rutas, incidencias y diff.</div></aside></div>{static_index}</main><script type="application/json" id="queryflow-payload">{payload}</script><script>{script}</script></body></html>"""


def write_detailed_html(
    campaign_root: Path,
    report: Mapping[str, Any],
    *,
    output_path: Path | None = None,
    context_lines: int = 3,
    diff_index: Mapping[str, Any] | None = None,
) -> Path:
    """Build and write the self-contained analyst HTML report."""
    campaign_root = Path(campaign_root).expanduser().resolve()
    if diff_index is None:
        diff_index = build_embedded_diff_index(
            report, campaign_root, context_lines=context_lines
        )
    target = (
        Path(output_path).expanduser()
        if output_path
        else campaign_root / "campaign-detail-report.html"
    )
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_detailed_html(report, diff_index) + "\n", encoding="utf-8")
    return target


def write_detailed_reports(
    campaign_root: Path,
    *,
    expected_count: int | None = None,
    output_base: Path | None = None,
) -> tuple[Path, Path]:
    """Generate ``campaign-detail-report.json`` and ``.md`` in the campaign root."""
    campaign_root = Path(campaign_root).expanduser().resolve()
    report = build_detailed_report(campaign_root, expected_count=expected_count)
    base = Path(output_base).expanduser() if output_base else campaign_root / "campaign-detail-report"
    base.parent.mkdir(parents=True, exist_ok=True)
    json_path = base.with_suffix(".json")
    markdown_path = base.with_suffix(".md")
    portable = _portable_report(report)
    json_path.write_text(json.dumps(portable, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    markdown_path.write_text(render_detailed_markdown(portable) + "\n", encoding="utf-8")
    return json_path, markdown_path


__all__ = [
    "REPORT_SCHEMA_VERSION",
    "DIFF_PAYLOAD_SCHEMA_VERSION",
    "build_detailed_report",
    "build_embedded_diff_index",
    "render_detailed_html",
    "render_detailed_markdown",
    "write_detailed_html",
    "write_detailed_reports",
]
